name: Build and Push Image
on:
  push:
    branches: [main]
    paths: ["app/**"]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get ECR repo
        id: ssm
        run: |
          ECR_REPO=$(aws ssm get-parameter --name "/bluegreen/prod/ecr_repo_name" --query "Parameter.Value" --output text)
          echo "ecr_repo_name=$ECR_REPO" >> $GITHUB_OUTPUT
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        env:
          ECR_REPO_NAME: ${{ steps.ssm.outputs.ecr_repo_name }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          TAG=${GITHUB_SHA::12}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"
          docker build -t "${ECR_REPO_NAME}:${TAG}" app
          docker tag "${ECR_REPO_NAME}:${TAG}" "${ECR_URI}:${TAG}"
          docker push "${ECR_URI}:${TAG}"
          aws ssm put-parameter --name "/bluegreen/prod/image_tag" --value "$TAG" --type String --overwrite --region $AWS_REGION
