# EC2 dynamic inventory for dev. Use: -i inventory/ec2_dev.aws_ec2.yml
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostnames:
  - instance-id
filters:
  instance-state-name: running
  tag:Env: dev
keyed_groups:
  - key: tags.Env
    prefix: env
